#!/bin/bash

echo "Cleaning image..."

if hash apt-get 2>/dev/null
then
  apt-get -y --purge autoremove
  apt-get -y clean
fi

rm -rf \
  "/tmp/"* \
  "/var/tmp/"* \
  "/var/lib/apt/lists/"* \
  "/var/log/alternatives.log" \
  "/var/log/apt/" \
  "/var/log/bootstrap.log" \
  "/var/log/btmp" \
  "/var/log/dpkg.log" \
  "/var/log/faillog" \
  "/var/log/fsck/" \
  "/var/log/lastlog" \
  "/var/log/wtmp"

find "/var/cache/" ! -type d -exec rm '{}' \;

echo "Image cleaned."
